// <auto-generated />
namespace TakipSistemi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class gamze : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(gamze));
        
        string IMigrationMetadata.Id
        {
            get { return "202209011210526_gamze"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
